In [16]:
#导包
import numpy as np

# 1.Numpy的属性介绍

## 1.1创建ndarray对象

In [17]:
#numpy → 和数学操作相关的库，numpy的数组是多维的，并且是固定类型的，numpy的数组是ndarray，主要用于矩阵运行
#1.创建numpy的ndarray对象
arr1 = np.arange(15).reshape(3,5)
print(arr1)
# arr2 = np.zeros((2,3,4))
# print(arr2.ndim)
# print(arr2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


## 1.2.演示 numpy 的常用属性

In [18]:
print(f'numpy的轴： {arr1.ndim}')
print(f'numpy的维度：{arr1.shape}')
print(f'numpy的元素类型： {arr1.dtype}')
print(f'numpy的元素个数：{arr1.size}')
print(f'numpy的元素占用的字节数：{arr1.itemsize}')
print(f'numpy的元素类型：{type(arr1)}')

numpy的轴： 2
numpy的维度：(3, 5)
numpy的元素类型： int64
numpy的元素个数：15
numpy的元素占用的字节数：8
numpy的元素类型：<class 'numpy.ndarray'>


# 2.创建Numpy数组的ndarray对象

## 2.1array()函数，把python列表->ndarray对象

In [21]:
# 1.创建python列表对象
my_list=[11,22,33,44]
print(type(my_list))
# 2.把python列表->ndarray对象
arr2=np.array(my_list)
print(arr2)  # [11 22 33 44]
print(type(arr2))  # <class 'numpy.ndarray'>

<class 'list'>
[11 22 33 44]
<class 'numpy.ndarray'>


## 2.2 arange()函数，创建ndarray对象

In [23]:
# arange(起始，结束，步长，dtype=类型)，类似于：python中的arange()函数。
# 1.创建ndarray对象
arr3 = np.arange(0,10,2,dtype=np.int64)
# 2.打印ndarray对象
print(arr3)
print(type(arr3))
print(f'numpy的dtype类型：{arr3.dtype}')

[0 2 4 6 8]
<class 'numpy.ndarray'>
numpy的dtype类型：int64


## 2.3随机矩阵生成 ndarray 对象

In [ ]:
# 1.random.rand() 生成0.0~1.0之间，包括左但不包括右的 随机小数矩阵
arr4 = np.random.rand(3,5)
print(arr4)
print(type(arr4))

[[0.62253498 0.84700546 0.49254258 0.03512104 0.1967667 ]
 [0.71068559 0.99688569 0.03521485 0.09796745 0.43528182]
 [0.34189672 0.75426633 0.3337819  0.78733714 0.38066927]]


In [ ]:
# 2.random.randint(起始值，结束值，size=（行，列）)生成指定范围，包左不包右的随机证书矩阵
arr5 = np.random.randint(3,9,size=(2,6))
print(arr5)
print(type(arr5))

[[8 3 4 6 7 3]
 [3 3 5 7 3 8]]
<class 'numpy.ndarray'>


In [29]:
# 3.random.uniform(起始值, 结束值， size=(行，列))生成指定范围，包左不包右，随机小数矩阵
arr6 = np.random.uniform(3,5,size=(4,3))
print(arr6)
print(type(arr6))

[[3.71676442 4.72521106 3.12497307]
 [4.15965858 4.11266433 3.5458747 ]
 [4.55088308 3.09398749 3.8834037 ]
 [4.97238706 3.98777591 3.92089729]]
<class 'numpy.ndarray'>


## 2.4 numpy的类型转换 astype()

In [31]:
# 1.创建ndarray对象
arr7 = np.arange(0, 10, 2, dtype=np.int64)
print(arr7)
print(arr7.dtype)

[0 2 4 6 8]
int64


In [33]:
# 2. 把上述的arr7 ndarray对象的元素 从int64 -> float32
arr8 = arr7.astype(np.float32)
print(arr8)
print(arr8.dtype)


[0. 2. 4. 6. 8.]
float32
