In [1]:
#导包
import numpy as np

# 1.Numpy的属性介绍

## 1.1创建ndarray对象

In [2]:
#numpy → 和数学操作相关的库，numpy的数组是多维的，并且是固定类型的，numpy的数组是ndarray，主要用于矩阵运行
#1.创建numpy的ndarray对象
arr1 = np.arange(15).reshape(3,5)
print(arr1)
# arr2 = np.zeros((2,3,4))
# print(arr2.ndim)
# print(arr2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


## 1.2.演示 numpy 的常用属性

In [3]:
print(f'numpy的轴： {arr1.ndim}')
print(f'numpy的维度：{arr1.shape}')
print(f'numpy的元素类型： {arr1.dtype}')
print(f'numpy的元素个数：{arr1.size}')
print(f'numpy的元素占用的字节数：{arr1.itemsize}')
print(f'numpy的元素类型：{type(arr1)}')

numpy的轴： 2
numpy的维度：(3, 5)
numpy的元素类型： int64
numpy的元素个数：15
numpy的元素占用的字节数：8
numpy的元素类型：<class 'numpy.ndarray'>


# 2.创建Numpy数组的ndarray对象

## 2.1array()函数，把python列表->ndarray对象

In [4]:
# 1.创建python列表对象
my_list=[11,22,33,44]
print(type(my_list))
# 2.把python列表->ndarray对象
arr2=np.array(my_list)
print(arr2)  # [11 22 33 44]
print(type(arr2))  # <class 'numpy.ndarray'>

<class 'list'>
[11 22 33 44]
<class 'numpy.ndarray'>


## 2.2 arange()函数，创建ndarray对象

In [5]:
# arange(起始，结束，步长，dtype=类型)，类似于：python中的arange()函数。
# 1.创建ndarray对象
arr3 = np.arange(0,10,2,dtype=np.int64)
# 2.打印ndarray对象
print(arr3)
print(type(arr3))
print(f'numpy的dtype类型：{arr3.dtype}')

[0 2 4 6 8]
<class 'numpy.ndarray'>
numpy的dtype类型：int64


## 2.3随机矩阵生成 ndarray 对象

In [6]:
# 1.random.rand() 生成0.0~1.0之间，包括左但不包括右的 随机小数矩阵
arr4 = np.random.rand(3,5)
print(arr4)
print(type(arr4))

[[0.21765701 0.80049264 0.99301596 0.00265955 0.36234277]
 [0.87340342 0.82254673 0.74128482 0.68984783 0.0382427 ]
 [0.55139295 0.13033135 0.30710702 0.7095966  0.91601248]]
<class 'numpy.ndarray'>


In [7]:
# 2.random.randint(起始值，结束值，size=（行，列）)生成指定范围，包左不包右的随机证书矩阵
arr5 = np.random.randint(3,9,size=(2,6))
print(arr5)
print(type(arr5))

[[7 3 3 6 6 8]
 [5 8 4 7 3 5]]
<class 'numpy.ndarray'>


In [8]:
# 3.random.uniform(起始值, 结束值， size=(行，列))生成指定范围，包左不包右，随机小数矩阵
arr6 = np.random.uniform(3,5,size=(4,3))
print(arr6)
print(type(arr6))

[[4.73057567 4.472454   3.68759044]
 [4.61908377 3.71125396 3.9931167 ]
 [3.343679   3.33214204 3.60965608]
 [3.02570596 3.84907943 4.38700021]]
<class 'numpy.ndarray'>


## 2.4 numpy的类型转换 astype()

In [9]:
# 1.创建ndarray对象
arr7 = np.arange(0, 10, 2, dtype=np.int64)
print(arr7)
print(arr7.dtype)

[0 2 4 6 8]
int64


In [10]:
# 2. 把上述的arr7 ndarray对象的元素 从int64 -> float32
arr8 = arr7.astype(np.float32)
print(arr8)
print(arr8.dtype)


[0. 2. 4. 6. 8.]
float32


## 2.5创建等比数列

In [11]:
# 1.创建等比数列 logspace(起始值，结束值，元素个数，base=底数（默认为10）)
arr9 = np.logspace(0,3,4)
print(arr9)
print(arr9.dtype)
arr10 = np.logspace(0,3,4,base=2)
print(arr10)
print(arr10.dtype)

[   1.   10.  100. 1000.]
float64
[1. 2. 4. 8.]
float64


## 2.6创建等差数列

In [12]:
# 1.创建等差数列 linspace(起始值，结束值，元素个数，endpoint=是否包含结束值，dtype=修改数据类型)
arr11 = np.linspace(1,10,4,endpoint=False,dtype=np.int32)
print(arr11)
print(arr11.dtype)

[1 3 5 7]
int32


# 3.1 基本函数

In [13]:
# 1.创建标准正太分布的序列
arr1 = np.random.randn(3,5)
print(arr1)

[[ 0.15567385 -1.6716782   2.18076864 -1.90234073  0.23676114]
 [ 0.26734757 -0.35521897  0.48603702 -0.49545872  0.38254073]
 [ 0.54532595  0.46378823 -0.68947679  0.13064263  0.34761314]]


In [14]:
# 2.测试基本函数
# print(np.ceil(arr1)) #天花板函数 ——> 向上取整
# print(np.floor(arr1)) #地板——>向下取整
# print(np.abs(arr1)) #绝对值
# print(np.rint(arr1))   #四舍五入
# print(np.multiply(arr1,arr1)) #矩阵乘法(行列数一致)
# print(arr1 * arr1) #效果同上
# print(np.divide(arr1,arr1))#矩阵除法(行列数一致)
print(np.where(arr1>0,1,-5))#类似与python中的三元表达式

[[ 1 -5  1 -5  1]
 [ 1 -5  1 -5  1]
 [ 1  1 -5  1  1]]


## 3.2统计函数

In [15]:
# 1.定义narray对象(数组对象)
arr1 = np.arange(12).reshape(3,4)
print(arr1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [16]:
# 2.验证累加和
print(np.cumsum(arr1))

[ 0  1  3  6 10 15 21 28 36 45 55 66]


In [17]:
# 2. 验证求和
print(np.sum(arr1))
print(np.sum(arr1, axis=0)) # 0　－－＞　列
print(np.sum(arr1, axis=1))  # 1　－－＞　行

66
[12 15 18 21]
[ 6 22 38]


## 3.3去重函数

In [18]:
# 1.定义数组
arr1 = np.array([[1, 2, 1], [2, 3, 5]])
print(arr1)

[[1 2 1]
 [2 3 5]]


In [19]:
# 2.对上述元素去重
arr2 = np.unique(arr1)
print(f'arr1= {arr1}')
print(f'arr2= {arr2}')

arr1= [[1 2 1]
 [2 3 5]]
arr2= [1 2 3 5]


## 3.4排序函数

In [20]:
# 1.定义数组
arr1 = np.array([11,33,88,66,44,55])
# 2.通过 np.sort() 来进行排序
arr2 =np.sort(arr1)
print(f'arr1= {arr1}')
print(f'arr2= {arr2}')
# 3.通过 数组对象 .sort() ->直接修改原数组
print(f'排序前 arr1: {arr1}')
arr1.sort()
print(f'排序后 arr1 : {arr1}')

arr1= [11 33 88 66 44 55]
arr2= [11 33 44 55 66 88]
排序前 arr1: [11 33 88 66 44 55]
排序后 arr1 : [11 33 44 55 66 88]


# 4 numpy的矩阵运算

## 4.1 加法运算

In [21]:
# 1.定义数组
arr1 = np.array([10,20,30,40])
arr2 = np.arange(4)
# 2.打印数组
print(f'arr1 = {arr1}')
print(f'arr2 = {arr2}')

arr1 = [10 20 30 40]
arr2 = [0 1 2 3]


In [22]:
# 3.减法运算
print(arr1-arr2)
# 4.加法运算
print(arr1+arr2)

[10 19 28 37]
[10 21 32 43]


## 4.2矩阵乘法

In [23]:
# 1.定义数组
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[4, 5], [7, 8], [3, 9]])
# 2.打印数组
print(f'arr1 = {arr1}')
print(f'arr2 = {arr2}')

arr1 = [[1 2 3]
 [4 5 6]]
arr2 = [[4 5]
 [7 8]
 [3 9]]


In [24]:
# 3.矩阵乘法,行列数一致
print(arr1*arr1)
print(np.multiply(arr1,arr1))

[[ 1  4  9]
 [16 25 36]]
[[ 1  4  9]
 [16 25 36]]


In [25]:
# 4.矩阵乘法,行列数不一致
# print(arr1*arr2) #行列数不一致,报错
# print(np.multiply(arr1,arr2)) # 报错同上
print(arr1 @ arr2)#语法糖  A列 = B行即可操作
print(np.dot(arr1,arr2))
print(arr1.dot(arr2))#效果同上

[[ 27  48]
 [ 69 114]]
[[ 27  48]
 [ 69 114]]
[[ 27  48]
 [ 69 114]]
